```{r}
library(ggmap)
library(readr)
library(ggplot2)
library(mapproj)
library(leaflet)
library(dplyr)
library(magrittr)

#匯入105年資料

A1_df<-read_csv("A1配對結果.csv")
TP_c<-read_csv("測速照相臺北市.csv")
TP_c2<-cbind.data.frame(TP_c$經度,TP_c$緯度,TP_c$速限)
colnames(TP_c2)<-c("lon","lat","sp")
colnames(A1_df)<-c("X","lon","lat","ad","code")
A1_df<-A1_df[,c(2,3,5)]

A2_df_1<-read_csv("A2配對結果10000.csv")
A2_df_2<-read_csv("A2配對結果一萬筆之後.csv")
colnames(A2_df_1)<-c("X","lon","lat","ad","code")
A2_df_2<-A2_df_2[,c(1,2,3,5,6)]
colnames(A2_df_2)<-c("X","lon","lat","ad","code")
A2_df<-rbind(A2_df_1,A2_df_2)
A2_df<-A2_df[,c(2,3,5)]
```

```{r}
#整理A1+A2，計算每個測速點的車禍數量

A_df<-rbind(A1_df,A2_df)
A_df_sum<-A_df%>%
  select(code)%>%
  group_by(code)%>%
  summarise(sum = length(code))
A_df_sum<-A_df_sum[-1,]
lost<-data.frame(code=c("9","42","51","56","57","76","81"),sum=c("0","0","0","0","0","0","0"))
A_df_sum<-rbind(A_df_sum,lost)
A_df_sum<-cbind(A_df_sum,TP_c2$sp)
A_df_sum%>%
  arrange(desc(code))
colnames(A_df_sum)<-c("code","sum","sp")
A_df_sum[is.na(A_df_sum)]<-0
total<-as.numeric(A_df_sum$sum)
A_df_sum<-cbind(A_df_sum[,c(1,3)],total)

```


```{r}
#計算出不同速度限制的總車禍量
A_df_sp<-A_df_sum%>%
  select(total,sp)%>%
  group_by(sp)%>%
  summarise(n = length(sp),total = sum(total))

```

```{r}
#畫出統計圖
#0為不知速限為何
mean<-A_df_sp$total/A_df_sp$n
A_df_sp<-cbind(A_df_sp,mean)
plot(A_df_sp$sp,A_df_sp$mean,main = "速限與車禍數量關係圖",xlab = "速限",ylab = "車禍數量")

```



```{r}


map<-get_googlemap(center=c(121.54111, 25.07026), zoom=12, darken = c(0.3, "white") ,maptype = "roadmap") 
ggmap(map)+
  geom_point(aes(x = lon, y = lat), size = 0.1, col="red",data = A_df, alpha = 1)+
  stat_density2d(data = A_df, aes(x = lon, y=lat,fill = ..level.., alpha = ..level..),size = 0.01, bins = 16, geom = "polygon") +
  scale_fill_gradient(low = "green", high = "red",guide = FALSE)+scale_alpha(range = c(0, 0.3), guide = FALSE)

  

```
```{r}

ggmap(map)+
   geom_point(aes(x = lon, y = lat), size = 1, col="red",data = TP_c2, alpha = 1)+
   geom_density2d(data = TP_c2, aes(x = lon, y=lat), size = 0.3)


```
```{r}
ggmap(map)+
   geom_point(aes(x = lon, y = lat), size = 1, col="red",data = TP_c2, alpha = 1)+
   
   stat_density2d(data = TP_c2, aes(x = lon, y=lat,fill = ..level.., alpha = ..level..),size = 0.01, bins = 16, geom = "polygon") +
  scale_fill_gradient(low = "green", high = "red",guide = FALSE)+scale_alpha(range = c(0, 0.3), guide = FALSE)
```


```{r}
#pal<-colorBin(palette=c(green,yellow,red,purple),domain=c(TP_c2&速限),bins=c(40,50,60,70),pretty=TRUE,na.color=#808080,alpha=F)

#map <- leaflet() %>%
#  addTiles() %>% 
#  setView(lng = 121.54111, lat = 25.07026, zoom= 12 )%>%
#  addCircles(data = A_df ,radius = 10 ,color = 'blue')%>%
#  addMarkers(data = A_df,clusterOptions = markerClusterOptions())%>%
#  addCircles(data = TP_c2, weight = 1,radius = 100 ,color = 'red')

#map %>% addProviderTiles(providers$Thunderforest.Outdoors)

#叢集表示
#addMarkers(data = A1_df,clusterOptions = markerClusterOptions())%>%

```



```{r}

#library(scales) 使產生的圖可以放大縮小不變形
#library(rgdal)  讀入地圖檔案 http://www.naturalearthdata.com/downloads/110m-cultural-vectors/
#上傳到shiny.io的圖片必須放在同一資料夾的www資料夾

#https://rstudio.github.io/leaflet/basemaps.html
#http://leaflet-extras.github.io/leaflet-providers/preview/index.html

```



